-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 21:15:42 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `companyId` INT AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `joinDate` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`companyId`)  COMMENT '',
  INDEX `index` (`companyId` ASC)  COMMENT '',
  UNIQUE INDEX `companyId_UNIQUE` (`companyId` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`team` ;

CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `id` INT AUTO_INCREMENT COMMENT '',
  `companyId` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `formedDate` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index` (`id` ASC, `companyId` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `id` INT AUTO_INCREMENT COMMENT '',
  `companyId` INT NOT NULL COMMENT '',
  `teamId` INT NOT NULL COMMENT '',
  `code` VARCHAR(5) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NULL COMMENT '',
  `totalHours` INT NOT NULL COMMENT '',
  `startDate` DATETIME NOT NULL COMMENT '',
  `endDate` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index` (`id` ASC, `companyId` ASC, `code` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`requests` ;

CREATE TABLE IF NOT EXISTS `mydb`.`requests` (
  `id` INT AUTO_INCREMENT COMMENT '',
  `companyId` INT NOT NULL COMMENT '',
  `employeeId` INT NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NOT NULL COMMENT '',
  `requestDate` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index` (`companyId` ASC, `id` ASC, `employeeId` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT AUTO_INCREMENT COMMENT '',
  `companyId` INT NOT NULL COMMENT '',
  `teamId` INT NOT NULL COMMENT '',
  `name` VARCHAR(200) NOT NULL COMMENT '',
  `daysOff` INT NOT NULL COMMENT '',
  `specialDaysOff` INT NOT NULL COMMENT '',
  `joinDate` DATETIME NOT NULL COMMENT '',
  `endDate` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index` (`companyId` ASC, `id` ASC, `teamId` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`taskAssociations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`taskAssociations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`taskAssociations` (
  `companyId` INT NOT NULL COMMENT '',
  `employeeId` INT NOT NULL COMMENT '',
  `taskId` INT NOT NULL COMMENT '',
  INDEX `companyId_UNIQUE` (`companyId` ASC)  COMMENT '',
  INDEX `index` (`companyId` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`daysOff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`daysOff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`daysOff` (
  `companyId` INT NOT NULL COMMENT '',
  `employeeId` INT NOT NULL COMMENT '',
  `day` DATETIME NOT NULL COMMENT '',
  INDEX `index` (`companyId` ASC, `employeeId` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`specialDaysOff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`specialDaysOff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`specialDaysOff` (
  `companyId` INT NOT NULL COMMENT '',
  `employeeId` INT NOT NULL COMMENT '',
  `day` DATETIME NOT NULL COMMENT '',
  INDEX `index` (`companyId` ASC, `employeeId` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workedHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`workedHours` ;

CREATE TABLE IF NOT EXISTS `mydb`.`workedHours` (
  `companyId` INT NOT NULL COMMENT '',
  `employeeId` INT NOT NULL COMMENT '',
  `taskId` INT NOT NULL COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  `hours` INT NOT NULL COMMENT '',
  INDEX `index` (`companyId` ASC, `employeeId` ASC, `taskId` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
